### PR TITLE
Improve stub in av.data

### PR DESCRIPTION
**Pull request by laggykiller**

### CODE REVIEW

**Comment by WyattBlue** [comment]
I not sure why you're using `type = "data"` instead of `type: Literal["data"]`. I definitely prefer the latter over the former. 

Also, I'm not even sure if type is accessible here. I'm 80% sure it is but I don't want to risk it. You've submitted a lot of PRs afterall.

**Comment by laggykiller** [comment]
Pylance at strict mode is complaining about this:

image
image

Note that the Literal type is still recognized correctly:
image

**Comment by WyattBlue** [comment]
mypy doesn't report any issues with your example.

**Comment by laggykiller** [comment]
I see, let me change other PR for this...

**Comment by laggykiller** [comment]
I was able to confirm that the attribute could be accessed in `DataStream` and `SubtitleStream`

---
### Sample file video_with_data.mp4
[video_with_data.zip](https://github.com/PyAV-Org/PyAV/files/14483456/video_with_data.zip)
- Please unzip to get the mp4
- Created with `ffmpeg -i file_example_MP4_480_1_5MG.mp4 -i data.txt -map_chapters 1 -c copy video_with_data.mp4`
- File sample from https://file-examples.com/index.php/sample-video-files/sample-mp4-files/
- data.txt:
```
;FFMETADATA1
major_brand=isom
minor_version=512
compatible_brands=isomiso2avc1mp41
encoder=Lavf60.5.100

[CHAPTER]
TIMEBASE=1/1000
START=00000
END=34000
title=Chapter
```

---
### Sample file subtitles.srt
- From https://github.com/moust/MediaPlayer/blob/master/demo/subtitles.srt

---

```python
import av

with av.open("subtitles.srt") as container:
    s = container.streams.subtitles[0].type
    print(s)

with av.open("video_with_data.mp4") as container:
    s = container.streams.data[0].type
    print(s)
```

Result:
```
subtitle
data
```

I have added this commit (https://github.com/laggykiller/PyAV/commit/5fc099ed154d75dec8ffd9a9a3139e339e7b41b0), please consider reopening and merge, thanks!

**Pull request closed without merging**
