### PR TITLE
[tests] use "h264" instead of "libx264" for tests (fixes: #951)

### PR DESCRIPTION
**Pull request by jlaine**
This allows running the test suite against FFmpeg builds which do not
have libx264 enabled.

### CODE REVIEW

**Comment by jlaine** [comment]
@deepsworld this one is for you. Changing "libx264" to "h264" doesn't seem to break the test suite *if libx264 is available*. I also tried removing libx264 support from our FFmpeg, but then things do start to break

**Comment by jlaine** [comment]
I think I'm most likely going to close this issue, it doesn't actually solve anything..

**Comment by hmaarrfk** [comment]
I think you need a few more patches:
https://github.com/conda-forge/av-feedstock/blob/main/recipe/lgpl_tests.patch

**Comment by hmaarrfk** [comment]
For more clarity, we at a conda-forge now build ffmpeg with (gpl) and without (lgpl) x264. 

We then compile pyav with lgpl, and then test it with the gpl and the lgpl versions. Without the patch I linked to, the lgpl-only tests would fail.

**Comment by hmaarrfk** [comment]
Nevermind, it seems that your patch is good. It actually includes the addition 5 line cleanup that I didn't include in mine due to not wanting to touch too many lines of code.

Did you build your FFMPEG builds with openh264? I'm happy to test the patch at conda-forge (where we have lgpl builds readily available).

**Review by hmaarrfk — APPROVED** [review]

**Pull request closed without merging**
