### PR TITLE
Remove unecessary clip in numpy example

### PR DESCRIPTION
**Pull request by hmaarrfk**
By the time you got to that line, the number is already a uint8, and cannot take any values outside of 0, 255.

### CODE REVIEW

**Comment by jlaine** [comment]
Could you rebase on top of `main` please?

**Comment by hmaarrfk** [comment]
ok... it was somewhat a 1 line change. I think asking to merge/rebase was a little much.

Is there a way to put me on an allow list to enable the CIs to run without your intervention?

**Comment by jlaine** [comment]
> Is there a way to put me on an allow list to enable the CIs to run without your intervention?

As soon as I merge any one of your PRs (probably this one!) you will be no longer be a "first time contributor" so CI will run automatically.

**Comment by hmaarrfk** [comment]
i see.

**Pull request merged**
