### PR TITLE
Add CI test for Win ffmpeg 4.4

### PR DESCRIPTION
**Pull request by uvjustin**
Use ffmpeg binary from ~https://github.com/BtbN/FFmpeg-Builds/releases~ pyav-ffmpeg.

### CODE REVIEW

**Comment by jlaine** [comment]
Hm. using third-party binary builds has bitten us in the backside in the past. I'm wondering if we should just use our own builds from pyav-ffmpeg if we cannot rely on conda anymore?

**Comment by uvjustin** [comment]
Yeah, we could just do that too. It does seem that something is wrong with the Windows conda builds.
FWIW the repo used is linked off the `[ffmpeg.org webpage](http://ffmpeg.org/download.html#build-windows)`,

**Comment by uvjustin** [comment]
Updated to use the pyav-ffmpeg binary

**Comment by jlaine** [comment]
Looks good to me, can you squash your commits please?

**Pull request merged**
