### PR TITLE
Improve typing

### PR DESCRIPTION
**Pull request by laggykiller**
Many typing is missing and incomplete. I have tried my best improve the typing stubs

### CODE REVIEW

**Comment by WyattBlue** [comment]
I'm not sure why you've replaced `list[str]` with `List[str]`. These are deprecated in Python 3.9, so shouldn't be used. We don't intent to support checking type-hints for Python <3.10.

Some changes look promising but it's too much to review in one PR. Consider splitting them to focus on one particular area.

**Comment by laggykiller** [comment]
I have removed `List`, `Tuple` and `Dict`, reformatted with black and sync with main.

Since many stubs are missing, and they import each other, it is a bit hard for me to split this PR... Do you mind suggesting what need to be changed here? I can make corrections.

**Comment by laggykiller** [comment]
I have tried my best to split this into 13 commits: https://github.com/laggykiller/PyAV/tree/improve-typing-split

Do you want me to close this and PR that branch? Or do you want me to open a PR for each of the 13 commits? I don't want to flood the repo with PR...

**Comment by laggykiller** [comment]
I have opened PR for first 5 commits (1306-1309)

Will open the rest after those get reviewed, as subsequent one may need modification based on review result

**Comment by laggykiller** [comment]
Review order recommendation:
1. 1306 + 1311; 1307; 1309; 1310 (merged); 1313; 1314; 1315; 1317; 1318
2. 1308 (need 1306); 1312 (need 1307); 1316 (need 1306)

**Comment by WyattBlue** [comment]
All done.

**Pull request closed without merging**
