### PR TITLE
Fix running doctests

### PR DESCRIPTION
**Pull request by jlaine**
We use `av.datasets` so explicitly import it

### CODE REVIEW

**Comment by jlaine** [comment]
@WyattBlue it looks as though the changes for FFmpeg 6 dropped compatibility with FFmpeg < 5.0. This is fine by me but then let's make 5.0 our baseline including in docs:

https://github.com/PyAV-Org/PyAV/blob/main/docs/overview/installation.rst?plain=1#L59

.. and the CI matrix.

**Comment by WyattBlue** [comment]
@jlaine Got it. Let's make https://github.com/PyAV-Org/PyAV/pull/1198 where we apply these changes.

**Comment by bedilbek** [comment]
@jlaine  I was just curious why have you decided to drop support for FFmpeg 4.x version, maybe at least support for 4.4 could be there for some more time

**Comment by WyattBlue** [comment]
@bedilbek We're dropping support for ffmpeg 5 full stop.

**Pull request merged**
