### PR TITLE
Create a path toward sharing memory from a numpy buffer

### PR DESCRIPTION
**Pull request by hmaarrfk**
I know there is some concern about having the memory aligned.

I didn't know if it needed to be aligned to 16 bits, or 16 bytes.

If you know let me know which it is, I can add a check for it. If you don't want to support this, then that is fine too.

Closes: https://github.com/PyAV-Org/PyAV/issues/1060

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@jlaine I didn't ask but are you interested in something like this? I've been using it with quite a bit of success more recently, I can add checks for continuous buffers too if you want.

**Comment by hmaarrfk** [comment]
anycomments on the desire to even support this kind of feature?

**Comment by hmaarrfk** [comment]
I've rebased this. this is ready for review.

**Comment by WyattBlue** [comment]
For the future, I'm okay with having numpy as a compile time dep if that meant PyAV was faster or smaller.

**Comment by hmaarrfk** [comment]
> For the future, I'm okay with having numpy as a compile time dep if that meant PyAV was faster or smaller.

Maybe we can discuss this in an issue

**Pull request merged**
