### PR TITLE
Allow setting the max_bit_rate and min_bit_rate in codec context

### PR DESCRIPTION
**Pull request by hmaarrfk**
These variables are documented as part of ffmpeg.

It might be useful for others to read and write them.

### CODE REVIEW

**Comment by jlaine** [comment]
OK could we have a test for this please?

**Comment by hmaarrfk** [comment]
I'm actually no longer sure *what* should happen when these things change. I had to specificy the codec context options dictionary to have a visible change in my output quality.

**Comment by jlaine** [comment]
I'm guessing this PR hasn't been rebased yet as the new tests are against `pypy3.9` and not `pypy3`?

**Comment by hmaarrfk** [comment]
I've rebased the patch, but I'm not sure what effect "writing" to these two properties has.

**Comment by WyattBlue** [comment]
This PR is too old.

**Pull request closed without merging**
