### PR TITLE
Add rgb48 and rgba64 pixel formats

### PR DESCRIPTION
**Pull request by apetrynet**
Hi!

I was testing out PyAV for a dailies/deliveries tool I'm writing and I noticed there was no support for uint16 data type in the numpy integration. 
With the added pixel types this PR I'm able to create ProRes video files based on 16bit images and maintain image quality.

I only added support for the little endian formats as I know too little on the matter and (_quite selfishly_) I don't know if I need support for big endian..

### CODE REVIEW

**Comment by jlaine** [comment]
Hi! This looks cool, thanks for putting it together. One thing leaves me a bit dubious: since we are talking about multi-byte formats, how do we know numpy's arrays are storing data in the expected endianness? Wouldn't this be platform-dependent?

**Comment by apetrynet** [comment]
Good point!
I can perhaps check the byteorder of the dtype and make sure it matches what the end user is asking for. I'll do some tests. Who knows, maybe I'll end up adding support for the rgb48be and rgba64be pixel formats after all :)

Thanks for the feedback!

**Review by L3wisXI — APPROVED** [review]

**Comment by jlaine** [comment]
Hi! Having recently fixed some endianness-related bugs in AudioFrame, I'm a little dubious about how this code works. I haven't forgot your PR though!

**Comment by apetrynet** [comment]
Hi!
Sorry about the late reply.
I'm not sure I understand. Are you saying my endianess-solution is a bit dodgy or that you don't quite get what I've done? 
It's been a while since I last looked at this so I'll need to refresh my memory in any case :)

**Comment by jlaine** [comment]
Hi @apetrynet I have added an alternative implementation in PR #939 

The key difference here is that the ndarray are always in the host's native system, which should help reduce confusion. Any thoughts on this?

**Comment by jlaine** [comment]
I'm closing this in favor of #939

**Comment by apetrynet** [comment]
Apologize again for late reply. I've been quite busy and I needed time to put my head into this again. 
Anyway, glad you managed to solve this in your PR.

**Pull request closed without merging**
