### PR TITLE
fix double free on extradata source in codec context

### PR DESCRIPTION
**Pull request by haohuanw**
https://github.com/PyAV-Org/PyAV/issues/640#issue-608274450

### CODE REVIEW

**Comment by haohuanw** [comment]
@jlaine would you be able to take a quick look on this PR?

**Comment by jlaine** [comment]
This looks like you're touching on a legitimate point, however doesn't the fix introduce a memory leak? When is this malloc'd memory freed?

**Comment by jlaine** [comment]
I had a look at the FFmpeg docs and it looks a little more involved than this:

- encoding: Set/allocated/freed by libavcodec.
- decoding: Set/allocated/freed by user.

https://ffmpeg.org/doxygen/4.0/structAVCodecContext.html#abe964316aaaa61967b012efdcced79c4

I'm not convinced we should allow setting `extradata` at all for encoders. For decoders, however it looks like we do own the memory and need to both allocate and free it. When we do perform allocation, I believe we need to add `AV_INPUT_BUFFER_PADDING_SIZE` to the extradata size.

**Comment by jlaine** [comment]
@haohuanw I provided an alternate approach in #756 could you let me know if it solves your problem?

**Comment by jlaine** [comment]
Fixed in #756

**Pull request closed without merging**
